# Generated by Django 3.2.14 on 2022-11-29 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('contrib_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('study_area', models.CharField(choices=[('Source-Control Strategies', 'Source-Control Strategies'), ('Resource-Directed Strategies', 'Resource-Directed Strategies'), ('Revival and Rehabilitation Strategies', 'Revival and Rehabilitation Strategies'), ('Overarching Strategies', 'Overarching Strategies')], default='Source-Control Strategies', max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('remarks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
