# Generated by Django 3.2.14 on 2022-11-30 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractResearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('counter', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('research', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fk_abstract_research', to='ndrppcwp_app.research')),
            ],
        ),
    ]
