# Generated by Django 3.2.14 on 2022-12-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0002_abstractresearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ('date_created',)},
        ),
    ]
