# Generated by Django 3.2.14 on 2022-12-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0005_auto_20221202_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='educational_prefixes',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='m_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='s_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
