# Generated by Django 3.2.14 on 2022-12-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0006_auto_20221202_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='publication_type',
            field=models.CharField(choices=[('Journal', 'Journal')], default='Journal', max_length=255),
        ),
    ]
