# Generated by Django 3.2.14 on 2023-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0009_alter_author_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='educational_prefixes',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='m_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='s_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
