# Generated by Django 3.2.14 on 2023-01-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0011_auto_20230104_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='URL',
            field=models.URLField(blank=True, default=''),
        ),
    ]
