# Generated by Django 3.2.14 on 2023-01-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0012_alter_research_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
