# Generated by Django 3.2.14 on 2023-03-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0015_alter_research_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='contrib_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
