# Generated by Django 3.2.14 on 2023-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0016_alter_research_contrib_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='educational_prefixes',
        ),
        migrations.AddField(
            model_name='author',
            name='prefixes',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Prof', 'Prof')], default='', max_length=255),
        ),
    ]
