# Generated by Django 3.2.14 on 2023-03-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0017_auto_20230308_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='prefixes',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Chan', 'Chan'), ('Miss', 'Miss'), ('Pres', 'Pres'), ('Prof', 'Prof'), ('Rep', 'Rep'), ('The Hon', 'The Hon')], default='', max_length=255),
        ),
    ]
