# Generated by Django 3.2.14 on 2023-03-09 02:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0018_alter_author_prefixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('org', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_report_error_research', to='ndrppcwp_app.research')),
            ],
        ),
    ]
