# Generated by Django 3.2.14 on 2023-03-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0019_reporterror'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportError',
        ),
    ]
