# Generated by Django 3.2.14 on 2023-03-09 04:08

from django.db import migrations, models
import ndrppcwp_app.helpers.file_validators


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0021_reporterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='categories',
            field=models.CharField(blank=True, choices=[('Scientific Journals', 'Scientific Journals'), ('Manuals', 'Manuals')], default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_pdf/%Y/%m/%d', validators=[ndrppcwp_app.helpers.file_validators.file_validator_valid_pdf_image]),
        ),
    ]
