# Generated by Django 3.2.14 on 2025-02-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0023_alter_reporterror_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='suffix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='m_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='prefixes',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Chan', 'Chan'), ('Miss', 'Miss'), ('Pres', 'Pres'), ('Prof', 'Prof'), ('Rep', 'Rep'), ('The Hon', 'The Hon')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='s_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='study_area',
            field=models.CharField(choices=[('Source-Control Strategies', 'SCS'), ('Resource-Directed Strategies', 'RDS'), ('Revival and Rehabilitation Strategies', 'RRS'), ('Overarching Strategies', 'OS')], default='Source-Control Strategies', max_length=255),
        ),
    ]
