# Generated by Django 3.2.14 on 2025-02-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0024_auto_20250225_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='contrib_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
