# Generated by Django 3.2.14 on 2025-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0025_alter_research_contrib_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='contrib_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
