# Generated by Django 3.2.14 on 2025-02-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0027_auto_20250225_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='prefixes',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mx', 'Mx'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Chan', 'Chan'), ('Miss', 'Miss'), ('Pres', 'Pres'), ('Prof', 'Prof'), ('Rep', 'Rep'), ('The Hon', 'The Hon')], default='', max_length=255),
        ),
    ]
