# Generated by Django 3.2.14 on 2025-02-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0028_author_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='custom_pub_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='custom_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='publication_type',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Others', 'Others')], default='Journal', max_length=255),
        ),
        migrations.AlterField(
            model_name='research',
            name='source_document',
            field=models.CharField(choices=[('Sylvatrop Technical Journal of the Philippine Ecosystems', 'Sylvatrop Technical Journal of the Philippine Ecosystems'), ('Natural Resources Volume 27 Nos. 1 and 2', 'Natural Resources Volume 27 Nos. 1 and 2'), ('Herdin', 'Herdin'), ('PCIEERD', 'PCIEERD'), ('ResearchGate', 'ResearchGate'), ('Others', 'Others')], default='Sylvatrop Technical Journal of the Philippine Ecosystems', max_length=255),
        ),
    ]
