# Generated by Django 3.2.14 on 2025-02-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0030_alter_author_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
