# Generated by Django 3.2.14 on 2025-03-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndrppcwp_app', '0031_alter_research_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='study_area',
            field=models.CharField(choices=[('Source-Control Strategies', 'Source-Control Strategies'), ('Resource-Directed Strategies', 'Resource-Directed Strategies'), ('Revival and Rehabilitation Strategies', 'Revival and Rehabilitation Strategies'), ('Overarching Strategies', 'Overarching Strategies')], default='Source-Control Strategies', max_length=255),
        ),
    ]
